# ExaBGP configuration — patroni-node2

process service {
    run /etc/exabgp/exabgp-run.sh;
    encoder text;
}

neighbor 172.32.0.1 {
    router-id 172.32.0.12;
    local-address 172.32.0.12;
    local-as 65001;
    peer-as 65000;
    hold-time 10;

    family {
        ipv4 unicast;
    }

    api {
        processes [service];
    }
}
