#!/usr/bin/env python3
"""
patroni-routing-bench: unified chart generation entry point.

Subcommands:
  iteration     --test-run-id ID [--output-dir PATH]
  combo-report  --combination-id ID --session-dir PATH --output PATH
  batch-report  --batch-csv PATH --batch-dir PATH --output PATH

Legacy (no subcommand):
  --combination-id ID | --test-run-id ID | --compare
"""
import argparse, base64, collections, html as _html, json, math, os, re, \
       statistics, subprocess, sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Optional

import pandas as pd
import psycopg
import plotly.graph_objects as go
import plotly.io as pio

# ── Style constants ───────────────────────────────────────────────────────────
STATE_COLORS = {
    "primary": "#2ecc71", "running": "#2ecc71", "UP":    "#2ecc71",
    "ok":      "#2ecc71", "bound":   "#2ecc71",
    "replica": "#3498db", "streaming": "#3498db",
    "stopped": "#e74c3c", "DOWN":    "#e74c3c", "fail":  "#e74c3c",
    "unreachable": "#95a5a6",
    "starting": "#f39c12", "creating replica": "#f39c12",
    "promote_requested": "#f39c12", "timeline_selected":      "#f39c12",
    "ready_accept_connections": "#2ecc71", "ready_readonly":  "#3498db",
    "entering_standby":  "#3498db",  "redo_starts":           "#f39c12",
    "consistent_recovery": "#3498db", "streaming_started":   "#3498db",
}
PHASE_COLORS = {
    "DCS Detection":     "#e67e22",
    "Patroni Promotion": "#f39c12",
    "Routing Detection": "#3498db",
    "Client Recovery":   "#2ecc71",
}
FONT_FAMILY = "Inter, Segoe UI, sans-serif"
WHITE       = "#ffffff"
DARK        = "#2c3e50"
GRAY        = "#95a5a6"
RED         = "#e74c3c"
GREEN       = "#2ecc71"
FOOTER_TEXT = "Generated by patroni-routing-bench"
OUTPUT_DIR  = Path(__file__).parent / "output"

# ── Color helpers ─────────────────────────────────────────────────────────────
def get_state_color(state: str) -> str:
    if not state:             return "#e74c3c"
    if state in STATE_COLORS: return STATE_COLORS[state]
    s = state.upper()
    if s.startswith("UP"):    return "#2ecc71"
    if s.startswith("DOWN"):  return "#e74c3c"
    return "#95a5a6"

def get_consul_color(event_type: str, new_value: str) -> str:
    if event_type == "leader_key_deleted": return "#e74c3c"
    if event_type in ("leader_key_created", "leader_key_change") and new_value: return "#2ecc71"
    return get_state_color(new_value or "")

def _haproxy_aggregate_color(server_states: dict) -> str:
    primary = {k: v for k, v in server_states.items() if k[0] == "primary_backend"}
    if not primary: return "#f39c12"
    return "#2ecc71" if any(str(v).upper().startswith("UP") for v in primary.values()) else "#e74c3c"

# ── DB / layout / kaleido helpers ─────────────────────────────────────────────
def get_connection():
    return psycopg.connect(
        "host={} port={} dbname={} user={} password={}".format(
            os.environ.get("TIMESCALE_HOST",     "localhost"),
            os.environ.get("TIMESCALE_PORT",     "5433"),
            os.environ.get("TIMESCALE_DB",       "bench"),
            os.environ.get("TIMESCALE_USER",     "bench"),
            os.environ.get("TIMESCALE_PASSWORD", "bench"),
        )
    )

def base_layout(title: str, width: int, height: int) -> dict:
    return dict(
        title=dict(text=title, font=dict(size=18, family=FONT_FAMILY, color=DARK)),
        font=dict(family=FONT_FAMILY, size=12, color=DARK),
        plot_bgcolor=WHITE, paper_bgcolor=WHITE,
        width=width, height=height,
        margin=dict(l=180, r=40, t=60, b=60),
        annotations=[dict(
            text=FOOTER_TEXT, xref="paper", yref="paper",
            x=1, y=-0.08, showarrow=False,
            font=dict(size=9, color=GRAY), xanchor="right",
        )],
    )

def _kaleido_major_version() -> int:
    try:
        import kaleido
        return int(getattr(kaleido, "__version__", "0").split(".")[0])
    except Exception:
        return 0

def _save_png(fig, path: Path, scale: int = 3):
    path.parent.mkdir(parents=True, exist_ok=True)
    if _kaleido_major_version() >= 1:
        path.write_bytes(pio.to_image(fig, format="png", scale=scale))
    else:
        fig.write_image(str(path), scale=scale)
    print(f"  Saved: {path}")

def _fig_to_b64(fig, scale: int = 2) -> Optional[str]:
    try:
        if _kaleido_major_version() >= 1:
            img = pio.to_image(fig, format="png", scale=scale)
        else:
            img = fig.to_image(format="png", scale=scale)
        return base64.b64encode(img).decode()
    except Exception as e:
        print(f"  Warning: chart rendering failed: {e}", file=sys.stderr)
        return None

def _plotly_html(fig) -> str:
    return pio.to_html(fig, include_plotlyjs="cdn", full_html=False,
                       config={"displayModeBar": False, "responsive": True})

# ── Resolve test run ──────────────────────────────────────────────────────────
def resolve_test_run(conn, test_run_id: Optional[str]) -> tuple[str, str]:
    """Return (test_run_id, combination_id). Uses most recent run if id not given."""
    with conn.cursor() as cur:
        if test_run_id:
            cur.execute("SELECT combination_id FROM test_runs WHERE id = %s", (test_run_id,))
            row = cur.fetchone()
            if row: return test_run_id, row[0]
            cur.execute(
                "SELECT DISTINCT combination_id FROM observer_events WHERE test_run_id = %s",
                (test_run_id,),
            )
            row = cur.fetchone()
            if row: return test_run_id, row[0]
            print(f"Error: test_run_id '{test_run_id}' not found.", file=sys.stderr)
            sys.exit(1)
        cur.execute("SELECT id, combination_id FROM test_runs ORDER BY started_at DESC LIMIT 1")
        row = cur.fetchone()
        if row: return row[0], row[1]
        cur.execute(
            "SELECT test_run_id, combination_id FROM observer_events ORDER BY ts DESC LIMIT 1"
        )
        row = cur.fetchone()
        if row: return row[0], row[1]
    print("Error: no events found in the database.", file=sys.stderr)
    sys.exit(1)

# ── Data loading ──────────────────────────────────────────────────────────────
def _query_df(conn, sql, params):
    with conn.cursor() as cur:
        cur.execute(sql, params)
        cols = [d[0] for d in cur.description]
        return pd.DataFrame(cur.fetchall(), columns=cols)

def load_observer_events(conn, cid, trid):
    return _query_df(conn, """
        SELECT ts, component, node, event_type, old_value, new_value, detail
        FROM observer_events
        WHERE combination_id = %(cid)s AND test_run_id = %(trid)s ORDER BY ts
    """, {"cid": cid, "trid": trid})

def load_client_events(conn, cid, trid):
    return _query_df(conn, """
        SELECT ts, success, latency_us, error FROM client_events
        WHERE combination_id = %(cid)s AND test_run_id = %(trid)s ORDER BY ts
    """, {"cid": cid, "trid": trid})

def load_failover_window(conn, cid, trid):
    with conn.cursor() as cur:
        cur.execute(
            "SELECT first_failure, last_failure, first_recovery, downtime_ms, total_failures"
            " FROM failover_window WHERE combination_id = %s AND test_run_id = %s",
            (cid, trid),
        )
        row = cur.fetchone()
    if not row: return None
    return {"first_failure": row[0], "last_failure": row[1],
            "first_recovery": row[2], "downtime_ms": row[3], "total_failures": row[4]}

def find_failover_anchor(conn, cid, trid):
    with conn.cursor() as cur:
        cur.execute("""
            SELECT ts FROM observer_events
            WHERE combination_id = %(cid)s AND test_run_id = %(trid)s
              AND (event_type = 'leader_key_deleted'
                   OR (event_type = 'role_change' AND new_value = 'primary'
                       AND old_value NOT IN ('none', 'uninitialized')))
            ORDER BY ts DESC LIMIT 1
        """, {"cid": cid, "trid": trid})
        row = cur.fetchone()
    return row[0] if row else None

def _load_windowed(conn, table, cid, trid, start, end, cols):
    return _query_df(conn, f"""
        SELECT {cols} FROM {table}
        WHERE combination_id = %(cid)s AND test_run_id = %(trid)s
          AND ts BETWEEN %(ws)s AND %(we)s ORDER BY ts
    """, {"cid": cid, "trid": trid, "ws": start, "we": end})

def load_windowed_observer(conn, cid, trid, s, e):
    return _load_windowed(conn, "observer_events", cid, trid, s, e,
                          "ts, component, node, event_type, old_value, new_value, detail")

def load_windowed_client(conn, cid, trid, s, e):
    return _load_windowed(conn, "client_events", cid, trid, s, e,
                          "ts, success, latency_us, error")

def load_run_data(conn, cid, run_id):
    """Load observer + client events, windowing if the dataset is large."""
    obs = load_observer_events(conn, cid, run_id)
    cli = load_client_events(conn, cid, run_id)
    if len(cli) > 5000 or (not cli.empty
            and (cli["ts"].max() - cli["ts"].min()).total_seconds() > 120):
        anchor = find_failover_anchor(conn, cid, run_id)
        if anchor:
            ws, we = anchor - pd.Timedelta(seconds=15), anchor + pd.Timedelta(seconds=45)
            obs = load_windowed_observer(conn, cid, run_id, ws, we)
            cli = load_windowed_client(conn, cid, run_id, ws, we)
    return obs, cli, load_failover_window(conn, cid, run_id)

# ── Milestone extraction ──────────────────────────────────────────────────────
def extract_milestones(obs_df: pd.DataFrame, cli_df: pd.DataFrame) -> dict:
    ms: dict = {}
    fail = cli_df[~cli_df["success"]]
    if not fail.empty:
        ms["first_client_failure"] = fail["ts"].min()
        after = cli_df[(cli_df["success"]) & (cli_df["ts"] > ms["first_client_failure"])]
        if not after.empty:
            ms["first_recovery"] = after["ts"].min()
    cdel = obs_df[obs_df["event_type"] == "leader_key_deleted"]
    if not cdel.empty:
        ms["consul_leader_deleted"] = cdel["ts"].iloc[-1]
    promo = obs_df[
        (obs_df["event_type"] == "role_change") & (obs_df["new_value"] == "primary")
        & (~obs_df["old_value"].isin(["none", "uninitialized"]))
    ]
    if not promo.empty:
        ms["patroni_promoted"] = promo["ts"].iloc[-1]
    ha_up = obs_df[
        (obs_df["event_type"] == "backend_state_change") & (obs_df["new_value"] == "UP")
        & (obs_df["detail"].str.contains("primary_backend", na=False))
    ]
    if not ha_up.empty:
        if "first_client_failure" in ms:
            ha_up = ha_up[ha_up["ts"] >= ms["first_client_failure"]]
        if not ha_up.empty:
            ms["haproxy_up"] = ha_up["ts"].iloc[0]
    pg_promo = obs_df[
        obs_df["event_type"].isin(["pg_promote_detected", "pg_promote_requested"])
    ]
    if not pg_promo.empty:
        ms["pg_promoted"] = pg_promo["ts"].iloc[-1]
    return ms

def extract_overlap_phases(obs_df: pd.DataFrame, cli_df: pd.DataFrame):
    """Per-phase spans measured independently (may overlap)."""
    phases: list = []
    first_failure = last_failure = first_recovery = None
    if not cli_df.empty:
        fail = cli_df[~cli_df["success"]]
        if not fail.empty:
            first_failure = fail["ts"].min()
            last_failure  = fail["ts"].max()
            after = cli_df[(cli_df["success"]) & (cli_df["ts"] > last_failure)]
            if not after.empty:
                first_recovery = after["ts"].min()
    cdel = obs_df[obs_df["event_type"] == "leader_key_deleted"]
    leader_deleted = cdel["ts"].iloc[-1] if not cdel.empty else None
    pg_req   = obs_df[obs_df["event_type"] == "pg_promote_requested"]
    pg_ready = obs_df[obs_df["event_type"] == "pg_ready_accept_connections"]
    pg_start = pg_req["ts"].iloc[-1] if not pg_req.empty else None
    pg_end   = None
    if not pg_ready.empty:
        cands = pg_ready[pg_ready["ts"] >= pg_start] if pg_start is not None else pg_ready
        if not cands.empty:
            pg_end = cands["ts"].iloc[0]
    ha_start = ha_end = None
    ha_ev = obs_df[obs_df["event_type"] == "backend_state_change"]
    if not ha_ev.empty:
        after = ha_ev[ha_ev["ts"] >= first_failure] if first_failure is not None else ha_ev
        if not after.empty:
            ha_start = after["ts"].iloc[0]
            up = after[after["new_value"].astype(str).str.upper().str.startswith("UP")]
            if "detail" in up.columns:
                pb = up[up["detail"].astype(str).str.contains("primary_backend", na=False)]
                if not pb.empty: up = pb
            if not up.empty: ha_end = up["ts"].iloc[0]

    def _add(name, start, end):
        if start is not None and end is not None:
            phases.append({"name": name, "start": start, "end": end,
                           "color": PHASE_COLORS.get(name, "#95a5a6"),
                           "instant": start == end})
    _add("DCS Detection",     first_failure, leader_deleted)
    _add("Patroni Promotion", pg_start, pg_end)
    _add("Routing Detection", ha_start, ha_end)
    _add("Client Recovery",   last_failure, first_recovery)
    return phases, {"first_failure": first_failure, "first_recovery": first_recovery}

# ── Chart builders ────────────────────────────────────────────────────────────
def build_gantt_chart(obs_df, cli_df, combination_id, total_downtime_s, title, subtitle=""):
    """Swimlane Gantt: one horizontal bar lane per component/node.

    Renders a pre-event initial-state bar for every lane so the viewer sees
    the healthy steady-state before the disruption begins.
    """
    lane_order = ["Client"]
    if not obs_df[obs_df["component"] == "haproxy"].empty:
        lane_order.append("HAProxy")
    if not obs_df[obs_df["component"] == "consul"].empty:
        lane_order.append("Consul")
    for node in sorted(obs_df[obs_df["component"] == "patroni"]["node"].unique()):
        lane_order.append(f"Patroni / {node.replace('patroni-', '')}")

    fig = go.Figure()
    obs_full = obs_df.copy()
    obs_df   = obs_df[~obs_df["event_type"].isin(["timeline_change"])].copy()
    all_ts   = pd.concat([obs_full["ts"], cli_df["ts"]])
    w_start, w_end = all_ts.min(), all_ts.max()

    # Client lane — runs of consecutive success/failure starting from w_start
    if not cli_df.empty:
        cli_s = cli_df.sort_values("ts")
        runs, cur_ok, r_start = [], cli_s.iloc[0]["success"], cli_s.iloc[0]["ts"]
        for _, row in cli_s.iterrows():
            if row["success"] != cur_ok:
                runs.append((r_start, row["ts"], cur_ok))
                cur_ok, r_start = row["success"], row["ts"]
        runs.append((r_start, cli_s.iloc[-1]["ts"], cur_ok))
        for start, end, ok in runs:
            fig.add_trace(go.Bar(
                x=[(end - start).total_seconds() or 0.1], y=["Client"],
                base=[(start - w_start).total_seconds()], orientation="h",
                marker=dict(color=get_state_color("ok" if ok else "fail")),
                showlegend=False,
                hovertext=f"Client: {'ok' if ok else 'fail'} "
                          f"({start.strftime('%H:%M:%S.%f')[:-3]} → {end.strftime('%H:%M:%S.%f')[:-3]})",
                hoverinfo="text",
            ))

    # Observer lanes
    for lane in lane_order:
        if lane == "Client": continue
        ha_states: dict = {}
        if lane == "HAProxy":
            ev = obs_df[obs_df["component"] == "haproxy"].sort_values("ts")
            is_ha, is_consul, node_sfx = True,  False, None
        elif lane == "Consul":
            ev = obs_df[obs_df["component"] == "consul"].sort_values("ts")
            is_ha, is_consul, node_sfx = False, True,  None
        elif lane.startswith("Patroni /"):
            node_sfx = lane.split("/ ")[1]
            ev = obs_df[(obs_df["component"] == "patroni")
                        & (obs_df["node"].str.contains(node_sfx))].sort_values("ts")
            is_ha, is_consul = False, False
        else:
            continue

        # Patroni node with no state-change events: full-window replica bar
        if ev.empty and node_sfx:
            fig.add_trace(go.Bar(
                x=[(w_end - w_start).total_seconds() or 0.1], y=[lane], base=[0],
                orientation="h", marker=dict(color="#3498db"), showlegend=False,
                hovertext=f"{lane}: replica (no state change)", hoverinfo="text",
            ))
            for _, tl in obs_full[(obs_full["component"] == "patroni")
                                  & (obs_full["node"].str.contains(node_sfx))
                                  & (obs_full["event_type"] == "timeline_change")].iterrows():
                fig.add_trace(go.Scatter(
                    x=[(tl["ts"] - w_start).total_seconds()], y=[lane], mode="markers",
                    marker=dict(symbol="diamond", size=11, color="#f39c12",
                                line=dict(color=DARK, width=1)),
                    showlegend=False,
                    hovertext=f"{lane}: timeline {tl['old_value']} → {tl['new_value']}",
                    hoverinfo="text",
                ))
            continue
        if ev.empty: continue

        # ── Pre-event initial-state bar (window start → first event) ──────────
        # Colour is derived from the first event's old_value so the viewer sees
        # the steady state (green=primary, blue=replica, etc.) before any change.
        first_ev = ev.iloc[0]
        init_dur = (first_ev["ts"] - w_start).total_seconds()
        if init_dur > 0.05:
            if is_ha:
                # Derive initial HAProxy aggregate from first event's old_value
                try:
                    d0 = json.loads(first_ev["detail"]) if first_ev["detail"] else {}
                    b0, s0 = d0.get("backend", ""), d0.get("server", "")
                    init_ha = {(b0, s0): first_ev["old_value"]} if b0 and s0 else {}
                    init_color = _haproxy_aggregate_color(init_ha) if init_ha else "#2ecc71"
                except Exception:
                    init_color = "#2ecc71"
                init_hover = "HAProxy: primary_backend UP (pre-failover)"
            elif is_consul:
                # If first event deletes the key, the leader existed just before → green
                if first_ev["event_type"] == "leader_key_deleted":
                    init_color = "#2ecc71"
                else:
                    init_color = get_consul_color(first_ev["event_type"],
                                                  str(first_ev.get("old_value") or ""))
                init_hover = "Consul: leader key present (pre-failover)"
            else:
                # Patroni: old_value of first event = role just before the event
                old_v = str(first_ev["old_value"] or "")
                if old_v in ("none", "uninitialized", ""):
                    old_v = "replica"
                init_color = get_state_color(old_v)
                init_hover = f"{lane}: {old_v} (pre-failover)"
            fig.add_trace(go.Bar(
                x=[init_dur], y=[lane], base=[0], orientation="h",
                marker=dict(color=init_color), showlegend=False,
                hovertext=init_hover, hoverinfo="text",
            ))

        # ── Event-driven state bars ───────────────────────────────────────────
        for i in range(len(ev)):
            row  = ev.iloc[i]
            start = row["ts"]
            end   = ev.iloc[i + 1]["ts"] if i + 1 < len(ev) else w_end
            if is_ha:
                try:
                    detail = json.loads(row["detail"]) if row["detail"] else {}
                    b, s = detail.get("backend", ""), detail.get("server", "")
                    if b and s: ha_states[(b, s)] = row["new_value"]
                except Exception:
                    pass
                color = _haproxy_aggregate_color(ha_states)
                hover = (f"HAProxy: {row['new_value']} — "
                         f"{str(row['detail'])[:80] if row['detail'] else ''} "
                         f"({start.strftime('%H:%M:%S.%f')[:-3]})")
            elif is_consul:
                color = get_consul_color(row["event_type"], row["new_value"])
                hover = (f"Consul: {row['event_type']} → {row['new_value']} "
                         f"({start.strftime('%H:%M:%S.%f')[:-3]})")
            else:
                color = get_state_color(row["new_value"])
                hover = (f"{lane}: {row['new_value']} "
                         f"({start.strftime('%H:%M:%S.%f')[:-3]})")
            fig.add_trace(go.Bar(
                x=[(end - start).total_seconds() or 0.1], y=[lane],
                base=[(start - w_start).total_seconds()], orientation="h",
                marker=dict(color=color), showlegend=False,
                hovertext=hover, hoverinfo="text",
            ))

    ms = extract_milestones(obs_df, cli_df)
    if "first_client_failure" in ms:
        x = (ms["first_client_failure"] - w_start).total_seconds()
        fig.add_vline(x=x, line=dict(color=RED, width=2, dash="dash"))
        fig.add_annotation(x=x, y=1.04, yref="paper", text="First Failure",
                           showarrow=False, font=dict(size=12, color=RED, family=FONT_FAMILY),
                           bgcolor="rgba(255,255,255,0.85)")
    if "first_recovery" in ms:
        x = (ms["first_recovery"] - w_start).total_seconds()
        fig.add_vline(x=x, line=dict(color=GREEN, width=2, dash="dash"))
        fig.add_annotation(x=x, y=1.04, yref="paper", text="Recovery",
                           showarrow=False, font=dict(size=12, color=GREEN, family=FONT_FAMILY),
                           bgcolor="rgba(255,255,255,0.85)")
    if total_downtime_s is not None:
        fig.add_annotation(x=0.5, y=-0.13, xref="paper", yref="paper",
                           text=f"<b>Total downtime: {total_downtime_s:.1f}s</b>",
                           showarrow=False, font=dict(size=13, color=DARK, family=FONT_FAMILY))

    # Legend entries — shortened labels so horizontal rows fit without overlap
    for label, color in [
        ("Primary / UP / Leader present / Success",  "#2ecc71"),
        ("Replica / Streaming",                      "#3498db"),
        ("Transitioning / No primary_backend data",  "#f39c12"),
        ("Failure / No UP / No leader / Stopped",    "#e74c3c"),
        ("Unreachable (expected after docker stop)", "#95a5a6"),
    ]:
        fig.add_trace(go.Bar(x=[0], y=[lane_order[0]], orientation="h",
                             marker=dict(color=color), name=label,
                             showlegend=True, visible="legendonly"))

    ds = f" — downtime {total_downtime_s:.1f}s" if total_downtime_s else ""
    title_html = f"{title}{ds}"
    if subtitle:
        title_html += f"<br><span style='font-size:12px;color:{GRAY}'>{subtitle}</span>"

    fig.update_layout(
        title=dict(text=title_html, font=dict(size=18, family=FONT_FAMILY, color=DARK),
                   pad=dict(b=10)),
        font=dict(family=FONT_FAMILY, size=13, color=DARK),
        plot_bgcolor=WHITE, paper_bgcolor=WHITE,
        width=1200, height=700,
        margin=dict(l=200, r=60, t=85, b=230),
        barmode="overlay",
        xaxis=dict(title="Time (seconds)", showgrid=True, gridcolor="#ecf0f1",
                   tickfont=dict(size=12)),
        yaxis=dict(categoryorder="array", categoryarray=list(reversed(lane_order)),
                   showgrid=False, tickfont=dict(size=13)),
        # Legend below the chart — avoids title/legend overlap entirely
        legend=dict(
            orientation="h", yanchor="top", y=-0.24,
            xanchor="center", x=0.5,
            font=dict(size=10, family=FONT_FAMILY),
            bgcolor="rgba(255,255,255,0.92)",
            bordercolor="#dde", borderwidth=1,
            itemsizing="constant",
        ),
    )
    return fig


def build_phase_chart(milestones: dict, combination_id: str, title: str, subtitle=""):
    """Single stacked horizontal bar showing sequential failover phases."""
    t0 = milestones.get("first_client_failure")
    if t0 is None: return None, {}

    def _dur(a, b):
        if a in milestones and b in milestones:
            return (milestones[b] - milestones[a]).total_seconds()
        return None

    phases = {}
    # Build adaptive phase chain based on available milestones
    # Order: failure → DCS → PG promotion → Patroni detection → routing → recovery
    available = []
    available.append(("first_client_failure", "Failure"))

    if "consul_leader_deleted" in milestones:
        available.append(("consul_leader_deleted", "DCS Detection"))
    if "pg_promoted" in milestones:
        available.append(("pg_promoted", "PG Promotion"))
    elif "patroni_promoted" in milestones:
        available.append(("patroni_promoted", "Patroni Promotion"))
    if "haproxy_up" in milestones:
        available.append(("haproxy_up", "Routing Detection"))
    if "first_recovery" in milestones:
        available.append(("first_recovery", "Client Recovery"))

    # Build phases from consecutive available milestones
    phase_list = []
    for i in range(len(available) - 1):
        key_a = available[i][0]
        key_b = available[i + 1][0]
        label = available[i + 1][1]
        phase_list.append((label, key_a, key_b))

    for name, a, b in phase_list:
        d = _dur(a, b)
        if d is not None: phases[name] = d
    if not phases: return None, {}

    # Threshold below which a label is placed outside (to the right) of its bar
    _MIN_INSIDE_S = 0.5

    fig = go.Figure()
    cumulative = 0.0
    phase_order = ["DCS Detection", "PG Promotion", "Patroni Promotion", "Routing Detection", "Client Recovery"]
    for name in phase_order:
        dur = phases.get(name)
        if dur is None: continue
        label = f"{dur:.2f}s"
        if dur >= _MIN_INSIDE_S:
            tpos = "inside"
            inside_font  = dict(color="white",  size=13, family=FONT_FAMILY)
            outside_font = dict(color=DARK,      size=13, family=FONT_FAMILY)
        else:
            tpos = "outside"
            inside_font  = dict(color="white",  size=13, family=FONT_FAMILY)
            outside_font = dict(color=DARK,      size=13, family=FONT_FAMILY)
        fig.add_trace(go.Bar(
            x=[dur], y=[combination_id], base=[cumulative], orientation="h",
            marker=dict(color=PHASE_COLORS.get(name, GRAY)), name=name,
            text=label, textposition=tpos,
            insidetextfont=inside_font,
            outsidetextfont=outside_font,
            hovertext=f"{name}: {dur:.2f}s", hoverinfo="text",
        ))
        cumulative += dur

    # Total annotation at the right end of the stacked bar
    fig.add_annotation(
        x=cumulative, y=combination_id,
        text=f"<b>Total: {cumulative:.2f}s</b>",
        xanchor="left", yanchor="middle",
        showarrow=False,
        font=dict(size=13, color=DARK, family=FONT_FAMILY),
        xshift=6,
    )

    title_text = (f"{title}<br><sup><span style='color:#666;font-size:12px'>{subtitle}</span></sup>"
                  if subtitle else title)
    fig.update_layout(
        title=dict(text=title_text, font=dict(size=18, family=FONT_FAMILY, color=DARK)),
        font=dict(family=FONT_FAMILY, size=13, color=DARK),
        plot_bgcolor=WHITE, paper_bgcolor=WHITE,
        width=1200, height=360, margin=dict(l=180, r=140, t=70, b=70),
        barmode="stack",
        xaxis=dict(title="Time (s from first failure)", showgrid=True, gridcolor="#ecf0f1"),
        yaxis=dict(showgrid=False),
        legend=dict(orientation="h", yanchor="bottom", y=1.08, xanchor="right", x=1),
    )
    return fig, phases


def build_overlap_phase_chart(phases: list, markers: dict, combination_id: str, title: str, subtitle=""):
    """Each phase on its own lane; spans are independent (may overlap)."""
    if not phases: return None
    all_ts = [p["start"] for p in phases] + [p["end"] for p in phases]
    if markers.get("first_failure"):    all_ts.append(markers["first_failure"])
    if markers.get("first_recovery"):   all_ts.append(markers["first_recovery"])
    w_start, w_end = min(all_ts), max(all_ts)
    lane_names = [p["name"] for p in phases]
    fig = go.Figure()

    # Grey shaded gap between Routing Detection end and Client Recovery start
    # (connection re-establishment window)
    _routing_end = None
    _client_start = None
    for p in phases:
        if p["name"] == "Routing Detection":
            _routing_end = p["end"]
        if p["name"] == "Client Recovery":
            _client_start = p["start"]
    if _routing_end and _client_start and _client_start > _routing_end:
        gap_x0 = (_routing_end  - w_start).total_seconds()
        gap_x1 = (_client_start - w_start).total_seconds()
        gap_s  = (gap_x1 - gap_x0)
        fig.add_shape(
            type="rect",
            x0=gap_x0, x1=gap_x1,
            y0=-0.5, y1=len(lane_names) - 0.5,
            yref="y",
            fillcolor="rgba(180,180,180,0.18)",
            line=dict(width=0),
            layer="below",
        )
        fig.add_annotation(
            x=(gap_x0 + gap_x1) / 2,
            y=len(lane_names) - 0.5,
            yref="y",
            text=f"conn re-establishment<br>({gap_s:.2f}s)",
            showarrow=False,
            font=dict(size=11, color="#888", family=FONT_FAMILY),
            align="center",
            yanchor="bottom",
            bgcolor="rgba(255,255,255,0.80)",
        )

    for p in phases:
        dur_s  = (p["end"] - p["start"]).total_seconds()
        base_s = (p["start"] - w_start).total_seconds()
        label  = "instant" if p.get("instant") else f"{dur_s:.2f}s"
        hover  = (f"{p['name']}: {p['start'].strftime('%H:%M:%S.%f')[:-3]} → "
                  f"{p['end'].strftime('%H:%M:%S.%f')[:-3]} ({dur_s:.3f}s)")
        fig.add_trace(go.Bar(
            x=[max(dur_s, 0.05)], y=[p["name"]], base=[base_s], orientation="h",
            marker=dict(color=p["color"]), text=label, textposition="outside",
            textfont=dict(size=13, color=DARK, family=FONT_FAMILY),
            showlegend=False, hovertext=hover, hoverinfo="text",
        ))
    if markers.get("first_failure"):
        x = (markers["first_failure"] - w_start).total_seconds()
        fig.add_vline(x=x, line=dict(color=RED, width=2, dash="dash"))
        fig.add_annotation(x=x, y=1.05, yref="paper", text="First client failure",
                           showarrow=False, font=dict(size=11, color=RED, family=FONT_FAMILY))
    if markers.get("first_recovery"):
        x = (markers["first_recovery"] - w_start).total_seconds()
        fig.add_vline(x=x, line=dict(color=GREEN, width=2, dash="dash"))
        fig.add_annotation(x=x, y=1.05, yref="paper", text="Client recovery",
                           showarrow=False, font=dict(size=11, color=GREEN, family=FONT_FAMILY))

    title_text = (f"{title}<br><sup><span style='color:#666;font-size:12px'>{subtitle}</span></sup>"
                  if subtitle else title)
    fig.update_layout(
        title=dict(text=title_text, font=dict(size=18, family=FONT_FAMILY, color=DARK)),
        font=dict(family=FONT_FAMILY, size=13, color=DARK),
        plot_bgcolor=WHITE, paper_bgcolor=WHITE,
        width=1200, height=420, margin=dict(l=220, r=80, t=80, b=80),
        barmode="overlay",
        xaxis=dict(title="Time (s from earliest phase start)", showgrid=True, gridcolor="#ecf0f1"),
        yaxis=dict(categoryorder="array", categoryarray=list(reversed(lane_names)), showgrid=False),
    )
    return fig

# ── Legacy comparison charts (for --compare mode) ─────────────────────────────
def _resolve_latest_trid(conn, cid: str) -> str:
    """Return the latest test_run_id for a combination, or '' if none."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id FROM test_runs WHERE combination_id = %s ORDER BY started_at DESC LIMIT 1",
            (cid,),
        )
        row = cur.fetchone()
    return row[0] if row else ""

def _find_latest_failover_window(conn, cid: str, trid: str = ""):
    """Return (window_start, window_end, resolved_trid). Fixes the empty-trid bug."""
    resolved = trid or _resolve_latest_trid(conn, cid)
    if not resolved:
        return None, None, resolved
    anchor = find_failover_anchor(conn, cid, resolved)
    if not anchor:
        return None, None, resolved
    return anchor - pd.Timedelta(seconds=15), anchor + pd.Timedelta(seconds=30), resolved

def _save_legacy(fig, name: str):
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _save_png(fig, OUTPUT_DIR / f"{name}.png")
    try:
        fig.write_image(str(OUTPUT_DIR / f"{name}.svg"), format="svg")
        print(f"  Saved: {OUTPUT_DIR / name}.svg")
    except Exception:
        pass

def generate_comparison_downtime(conn):
    df = pd.read_sql(
        "SELECT combination_id, avg_downtime_ms, min_downtime_ms, max_downtime_ms "
        "FROM combination_comparison ORDER BY avg_downtime_ms", conn,
    )
    if df.empty:
        print("  No comparison data available.")
        return
    n = len(df)
    colors = [
        f"rgb({int(46+(231-46)*i/max(n-1,1))},{int(204+(76-204)*i/max(n-1,1))},{int(113+(60-113)*i/max(n-1,1))})"
        for i in range(n)
    ]
    fig = go.Figure(go.Bar(
        x=df["avg_downtime_ms"], y=df["combination_id"], orientation="h",
        marker=dict(color=colors),
        text=df["avg_downtime_ms"].apply(lambda x: f"{x:.0f} ms"), textposition="outside",
        error_x=dict(type="data", symmetric=False,
                     array=(df["max_downtime_ms"] - df["avg_downtime_ms"]).tolist(),
                     arrayminus=(df["avg_downtime_ms"] - df["min_downtime_ms"]).tolist(),
                     color=GRAY, thickness=1.5),
    ))
    fig.update_layout(**base_layout("Failover Downtime Comparison", 1000, 500),
                      xaxis=dict(title="Downtime (ms)", showgrid=True, gridcolor="#ecf0f1"),
                      yaxis=dict(showgrid=False))
    _save_legacy(fig, "comparison_downtime")

def generate_comparison_phases(conn):
    rows = []
    for cid in pd.read_sql(
        "SELECT DISTINCT combination_id FROM observer_events ORDER BY combination_id", conn,
    )["combination_id"]:
        ws, we, trid = _find_latest_failover_window(conn, cid)
        if ws is None: continue
        obs = load_windowed_observer(conn, cid, trid, ws, we)
        cli = load_windowed_client(conn, cid, trid, ws, we)
        ms = extract_milestones(obs, cli)
        if len(ms) < 2: continue
        def _dur(a, b): return (ms[b]-ms[a]).total_seconds() if a in ms and b in ms else 0
        rows.append({"combination_id": cid,
                     "DCS Detection":     _dur("first_client_failure",  "consul_leader_deleted"),
                     "Patroni Promotion": _dur("consul_leader_deleted",  "patroni_promoted"),
                     "Routing Detection": _dur("patroni_promoted",       "haproxy_up"),
                     "Client Recovery":   _dur("haproxy_up",             "first_recovery")})
    if not rows:
        print("  Not enough data for phase breakdown.")
        return
    df = pd.DataFrame(rows).set_index("combination_id").fillna(0)
    fig = go.Figure()
    for phase, color in PHASE_COLORS.items():
        if phase in df.columns:
            fig.add_trace(go.Bar(x=df[phase], y=df.index, name=phase,
                                 orientation="h", marker=dict(color=color)))
    fig.update_layout(**base_layout("Failover Phase Breakdown by Combination", 1000, 500),
                      barmode="stack",
                      xaxis=dict(title="Time (s)", showgrid=True, gridcolor="#ecf0f1"),
                      yaxis=dict(showgrid=False),
                      legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    _save_legacy(fig, "comparison_phases")

# ── Report: constants and HTML helpers ───────────────────────────────────────
SCENARIO_DESCRIPTIONS = {
    "hard_stop": (
        "SIGTERM — graceful Patroni shutdown. Patroni releases the DCS leader lock immediately "
        "and shuts down PostgreSQL cleanly. Tests the standard failover path."
    ),
    "hard_kill": (
        "SIGKILL — no shutdown hooks, no graceful cleanup. PostgreSQL and Patroni die instantly. "
        "The leader lock expires via TTL (up to 30 s). Tests TTL-based lock expiry."
    ),
    "network_partition": (
        "Network disconnect — container stays running but loses all connectivity. "
        "The leader lock expires via TTL. Tests split-brain prevention."
    ),
    "postgres_crash": (
        "PostgreSQL process killed inside the running container. Patroni detects the crash "
        "and attempts to restart it. Tests PG-level crash with Patroni still alive."
    ),
    "switchover": (
        "Planned patronictl switchover — zero-downtime maintenance path. Patroni stops writes, "
        "waits for the chosen replica to catch up, then promotes it."
    ),
    "pause": (
        "SIGSTOP — container frozen, no TCP RST. Consul TTL expires because Patroni can no longer "
        "send heartbeats. Tests pure TTL-based detection without connection resets."
    ),
}

_CSS = """\
*{box-sizing:border-box}
body{font-family:Arial,Helvetica,sans-serif;max-width:1440px;margin:0 auto;padding:24px 28px;
     color:#2c3e50;line-height:1.5;font-size:14px}
h1{color:#2c3e50;border-bottom:3px solid #3498db;padding-bottom:10px;margin-bottom:8px;font-size:24px}
h2{color:#3498db;border-bottom:1px solid #ecf0f1;padding-bottom:6px;margin-top:48px;font-size:19px}
h3{color:#7f8c8d;margin-top:24px;margin-bottom:8px;font-size:15px}
table{border-collapse:collapse;width:100%;margin:12px 0;font-size:13px}
th{background:#2c3e50;color:#fff;padding:7px 12px;text-align:left;white-space:nowrap}
td{padding:5px 12px;border-bottom:1px solid #ecf0f1;vertical-align:top}
tr:nth-child(even) td{background:#f9f9f9}
code{background:#f0f0f0;padding:1px 5px;border-radius:3px;font-size:12px;word-break:break-all}
.meta{background:#f8f9fa;border-left:4px solid #3498db;padding:14px 20px;
      border-radius:0 4px 4px 0;margin:16px 0}
.meta-grid{display:grid;grid-template-columns:max-content 1fr;gap:5px 24px}
.meta-label{font-weight:bold;color:#7f8c8d;white-space:nowrap}
.chart-img{max-width:100%;height:auto;margin:6px 0;display:block;border:1px solid #ecf0f1;border-radius:4px}
.iter-header{background:#ecf0f1;padding:10px 16px;border-left:4px solid #3498db;
             border-radius:0 4px 4px 0;margin-top:40px;margin-bottom:12px}
.badge{display:inline-block;padding:2px 10px;border-radius:10px;font-size:12px;font-weight:bold;color:#fff}
.badge-success{background:#27ae60}.badge-timeout{background:#e74c3c}
.badge-skipped{background:#f39c12}.badge-error,.badge-cluster_unhealthy{background:#95a5a6}
.badge-unknown{background:#bdc3c7}
.downtime{font-size:18px;font-weight:bold;color:#e74c3c}
.no-chart{color:#95a5a6;font-style:italic;padding:6px 0;font-size:13px}
footer{margin-top:60px;padding:20px 0;border-top:1px solid #ecf0f1;color:#95a5a6;font-size:12px}
footer ul{margin:6px 0;padding-left:20px}footer li{margin:3px 0}
"""

def _h(text) -> str:
    return _html.escape(str(text)) if text is not None else ""

def _badge(status: str) -> str:
    cls = f"badge badge-{status.lower()}"
    return f'<span class="{_h(cls)}">{_h(status)}</span>'

def _img_tag(b64: Optional[str], alt: str = "Chart") -> str:
    if b64:
        return f'<img class="chart-img" src="data:image/png;base64,{b64}" alt="{_h(alt)}">'
    return '<p class="no-chart">Chart not available — kaleido required</p>'

def _parse_session_date(ts: str) -> date:
    ts = ts.strip()
    for fmt in ("%Y-%m-%d", "%Y%m%d", "%Y%m%d_%H%M%S"):
        try: return datetime.strptime(ts, fmt).date()
        except ValueError: pass
    raise ValueError(f"Cannot parse session timestamp '{ts}'")

def _load_iter_charts(session_dir: Path, iter_num: int, scenario: str) -> dict:
    iter_dir = session_dir / f"iter{iter_num}_{scenario}"
    return {
        name: base64.b64encode((iter_dir / f"{name}.png").read_bytes()).decode()
        for name in ("failover_gantt", "failover_phases", "failover_phases_overlap")
        if (iter_dir / f"{name}.png").exists()
    }

def _infer_killed_leader(obs_df: pd.DataFrame) -> str:
    if obs_df.empty: return "—"
    dem = obs_df[
        (obs_df["component"] == "patroni") & (obs_df["event_type"] == "role_change")
        & (obs_df["old_value"].isin(["primary", "running"]))
        & (obs_df["new_value"].isin(["stopped", "unreachable", "replica"]))
    ]
    return dem.iloc[0]["node"].replace("patroni-", "") if not dem.empty else "—"

def _load_patroni_config(combination_id: str) -> dict:
    candidates = [
        Path(f"dcs/consul/{combination_id}/config/patroni.yml"),
        Path(__file__).parent.parent.parent / f"dcs/consul/{combination_id}/config/patroni.yml",
    ]
    path = next((p for p in candidates if p.exists()), None)
    if path is None: return {}
    text = path.read_text()
    result: dict = {"patroni_yml": str(path)}
    for key in ("ttl", "loop_wait", "retry_timeout"):
        m = re.search(rf"^\s+{key}:\s*(\d+)", text, re.MULTILINE)
        if m: result[key] = int(m.group(1))
    return result

def _load_session_runs(conn, combination_id: str, session_date: date) -> pd.DataFrame:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id, combination_id, failover_type, started_at, ended_at, notes "
            "FROM test_runs WHERE combination_id = %s AND started_at::date = %s ORDER BY started_at",
            (combination_id, session_date),
        )
        return pd.DataFrame(cur.fetchall(), columns=[d[0] for d in cur.description])

# ── Report: render functions ──────────────────────────────────────────────────
def _render_header(combination_id, session_date, patroni_cfg, runs_df, iterations) -> str:
    total = len(iterations)
    ok = sum(1 for it in iterations if it["status"] == "SUCCESS")
    pct = ok * 100 // total if total else 0
    scens = sorted(set(it["scenario"] for it in iterations if it["scenario"] != "unknown"))
    started = runs_df["started_at"].min().strftime("%Y-%m-%d %H:%M:%S UTC") if not runs_df.empty else "—"
    ended_r = runs_df["ended_at"].dropna().max() if not runs_df.empty else None
    ended   = ended_r.strftime("%Y-%m-%d %H:%M:%S UTC") if ended_r is not None and not pd.isna(ended_r) else "—"
    return f"""\
<h1>Failover Report — {_h(combination_id)}</h1>
<div class="meta"><div class="meta-grid">
  <span class="meta-label">Combination</span>   <span><code>{_h(combination_id)}</code></span>
  <span class="meta-label">Session date</span>  <span>{_h(str(session_date))}</span>
  <span class="meta-label">Started</span>       <span>{_h(started)}</span>
  <span class="meta-label">Ended</span>         <span>{_h(ended)}</span>
  <span class="meta-label">Scenarios</span>     <span>{_h(', '.join(scens) or '—')}</span>
  <span class="meta-label">Iterations</span>    <span>{total} ({ok} succeeded, {pct}%)</span>
  <span class="meta-label">Patroni TTL</span>   <span>{_h(str(patroni_cfg.get('ttl','—')))} s</span>
  <span class="meta-label">loop_wait</span>     <span>{_h(str(patroni_cfg.get('loop_wait','—')))} s</span>
  <span class="meta-label">retry_timeout</span> <span>{_h(str(patroni_cfg.get('retry_timeout','—')))} s</span>
  <span class="meta-label">patroni.yml</span>   <span><code>{_h(patroni_cfg.get('patroni_yml','not found'))}</code></span>
</div></div>
"""

def _render_summary_table(iterations) -> str:
    rows = ""
    for it in iterations:
        dt = it.get("downtime", "—")
        dt_str = f"{dt}s" if dt not in ("—", None, "") else "—"
        rows += (f"<tr><td>{_h(it.get('num',''))}</td><td><code>{_h(it.get('scenario',''))}</code></td>"
                 f"<td>{_h(it.get('leader',''))}</td><td>{_h(dt_str)}</td>"
                 f"<td>{_h(str(it.get('failed_queries','—')))}</td>"
                 f"<td>{_badge(it.get('status','UNKNOWN'))}</td>"
                 f"<td><code style='font-size:11px'>{_h(it.get('run_id',''))}</code></td></tr>\n")
    return (f"<h2>Summary</h2><table><thead><tr>"
            f"<th>#</th><th>Scenario</th><th>Leader Killed</th>"
            f"<th>Downtime</th><th>Failed Queries</th><th>Status</th><th>Run ID</th>"
            f"</tr></thead><tbody>\n{rows}</tbody></table>\n")

def _render_event_timeline(obs_df: pd.DataFrame, cli_df: pd.DataFrame) -> str:
    if obs_df.empty: return "<p>No observer events for this run.</p>"
    t0 = None
    if not cli_df.empty:
        fail = cli_df[~cli_df["success"]]
        if not fail.empty: t0 = fail["ts"].min()
    if t0 is None: t0 = obs_df["ts"].min()
    SIGNIFICANT = {"role_change", "leader_key_deleted", "leader_key_created", "leader_key_change",
                   "timeline_change", "backend_state_change", "vip_state_change",
                   "pg_promote_requested", "pg_ready_accept_connections"}
    df = obs_df[obs_df["event_type"].isin(SIGNIFICANT)].sort_values("ts").head(120)
    if df.empty: df = obs_df.sort_values("ts").head(120)
    rows = ""
    for _, row in df.iterrows():
        el = (row["ts"] - t0).total_seconds()
        sign = "+" if el >= 0 else ""
        old_v = _h(row.get("old_value") or "")
        new_v = _h(row.get("new_value") or "")
        arrow = f"{old_v} → {new_v}" if old_v else new_v
        rows += (f"<tr><td><code>{_h(f'{sign}{el:.3f}s')}</code></td>"
                 f"<td>{_h(row['ts'].strftime('%H:%M:%S.%f')[:-3])}</td>"
                 f"<td>{_h(row['component'])}</td><td>{_h(row['node'])}</td>"
                 f"<td><code>{_h(row['event_type'])}</code></td><td>{arrow}</td></tr>\n")
    cap = (f" <small style='color:#95a5a6'>(showing {len(df)} of {len(obs_df)})</small>"
           if len(obs_df) > len(df) else "")
    return (f"<h3>Event Timeline{cap}</h3><table><thead><tr>"
            f"<th>Elapsed</th><th>Time (UTC)</th><th>Component</th><th>Node</th>"
            f"<th>Event</th><th>Value</th></tr></thead><tbody>\n{rows}</tbody></table>\n")

def _render_phase_breakdown(phases: dict) -> str:
    if not phases: return ""
    total_s = sum(phases.values())
    rows = ""
    for name in ["DCS Detection", "Patroni Promotion", "Routing Detection", "Client Recovery"]:
        dur = phases.get(name)
        if dur is None: continue
        pct = dur / total_s * 100 if total_s > 0 else 0
        color = PHASE_COLORS.get(name, GRAY)
        swatch = (f'<span style="display:inline-block;width:12px;height:12px;'
                  f'background:{color};border-radius:2px;margin-right:6px;vertical-align:middle"></span>')
        rows += (f"<tr><td>{swatch}{_h(name)}</td><td>{dur:.3f} s</td><td>{pct:.0f}%</td></tr>\n")
    rows += (f"<tr style='font-weight:bold;border-top:2px solid #2c3e50'>"
             f"<td>Total</td><td>{total_s:.3f} s</td><td>100%</td></tr>\n")
    return (f"<h3>Phase Breakdown</h3>"
            f"<table style='width:auto;min-width:380px'><thead><tr>"
            f"<th>Phase</th><th>Duration</th><th>Share</th></tr></thead>"
            f"<tbody>\n{rows}</tbody></table>\n")

def _render_iteration_section(iter_num, run_row, obs_df, cli_df, fw,
                               status, leader, preloaded_charts=None) -> str:
    run_id = run_row["id"]
    scenario = run_row["failover_type"] or "unknown"
    cid      = run_row["combination_id"]
    started_str = (run_row["started_at"].strftime("%Y-%m-%d %H:%M:%S UTC")
                   if run_row["started_at"] is not None else "—")
    downtime_s = float(fw["downtime_ms"]) / 1000.0 if fw and fw.get("downtime_ms") else None
    downtime_str = f"{downtime_s:.2f} s" if downtime_s is not None else "—"
    desc = SCENARIO_DESCRIPTIONS.get(scenario, "")
    chart_title = f"Iteration {iter_num} — {scenario} — {cid}"
    gantt_b64 = phase_b64 = overlap_b64 = None
    phases: dict = {}

    if preloaded_charts is not None:
        gantt_b64   = preloaded_charts.get("failover_gantt")
        phase_b64   = preloaded_charts.get("failover_phases")
        overlap_b64 = preloaded_charts.get("failover_phases_overlap")
        if not obs_df.empty:
            _, phases = build_phase_chart(extract_milestones(obs_df, cli_df),
                                          cid, f"Phase Breakdown — {chart_title}")
    elif not obs_df.empty:
        ms = extract_milestones(obs_df, cli_df)
        gantt_fig = build_gantt_chart(obs_df, cli_df, cid, downtime_s, chart_title)
        gantt_b64 = _fig_to_b64(gantt_fig)
        phase_fig, phases = build_phase_chart(ms, cid, f"Phase Breakdown — {chart_title}")
        if phase_fig: phase_b64 = _fig_to_b64(phase_fig)
        ov_phases, ov_markers = extract_overlap_phases(obs_df, cli_df)
        ov_fig = build_overlap_phase_chart(ov_phases, ov_markers, cid,
                                            f"Phases (Overlapping) — {chart_title}")
        if ov_fig: overlap_b64 = _fig_to_b64(ov_fig)

    dt_display = (f'<span class="downtime">{_h(downtime_str)}</span>'
                  if downtime_s is not None else "<span style='color:#95a5a6'>—</span>")
    return f"""\
<div class="iter-header">
  <strong>Iteration {iter_num}</strong> &nbsp;—&nbsp; <code>{_h(scenario)}</code>
  &nbsp;&nbsp;{_badge(status)} &nbsp;&nbsp;Downtime: {dt_display}
  &nbsp;&nbsp;<span style="color:#7f8c8d;font-size:13px">{_h(started_str)}</span>
</div>
<p>{_h(desc)}</p>
<p style="font-size:12px;color:#95a5a6">
  Run ID: <code>{_h(run_id)}</code> &nbsp;&nbsp;Leader killed: <strong>{_h(leader)}</strong>
</p>
<h3>Failover Gantt</h3>{_img_tag(gantt_b64, f"Gantt — iteration {iter_num}")}
<h3>Phase Breakdown (Sequential)</h3>{_img_tag(phase_b64, f"Phases — iteration {iter_num}")}
<h3>Phase Breakdown (Overlapping)</h3>{_img_tag(overlap_b64, f"Overlap — iteration {iter_num}")}
{_render_phase_breakdown(phases)}
{_render_event_timeline(obs_df, cli_df)}
"""

def _render_comparison_section(iterations: list) -> str:
    ok_iters = [it for it in iterations if it.get("status") == "SUCCESS"]
    if len(ok_iters) < 2: return ""
    by_scen: dict = collections.defaultdict(list)
    for it in ok_iters:
        try: by_scen[it["scenario"]].append(float(it["downtime"]))
        except (TypeError, ValueError): pass
    if not by_scen: return ""
    scens = sorted(by_scen)
    means, stds, rows = [], [], ""
    for s in scens:
        vals = by_scen[s]; n = len(vals)
        mean = statistics.mean(vals); med = statistics.median(vals)
        std  = statistics.stdev(vals) if n > 1 else 0.0
        means.append(mean); stds.append(std)
        rows += (f"<tr><td><code>{_h(s)}</code></td><td>{n}</td>"
                 f"<td>{mean:.2f} s</td><td>{med:.2f} s</td>"
                 f"<td>{min(vals):.2f} s</td><td>{max(vals):.2f} s</td>"
                 f"<td>{std:.2f} s</td></tr>\n")
    bar = go.Figure(go.Bar(x=scens, y=means, marker_color="#3498db",
                           error_y=dict(type="data", array=stds, visible=True, thickness=2),
                           text=[f"{m:.2f} s" for m in means], textposition="outside"))
    bar.update_layout(title=dict(text="Mean Downtime by Scenario (±1 StdDev)",
                                 font=dict(size=16, family=FONT_FAMILY, color=DARK)),
                      font=dict(family=FONT_FAMILY), plot_bgcolor=WHITE, paper_bgcolor=WHITE,
                      width=900, height=400, margin=dict(l=60, r=40, t=60, b=80),
                      yaxis=dict(title="Downtime (s)", showgrid=True, gridcolor="#ecf0f1"),
                      showlegend=False)
    b64 = _fig_to_b64(bar)
    return (f"<h2>Comparison by Scenario</h2>{_img_tag(b64, 'Scenario comparison')}"
            f"<h3>Statistics by Scenario (successful iterations only)</h3>"
            f"<table><thead><tr><th>Scenario</th><th>N</th><th>Mean</th><th>Median</th>"
            f"<th>Min</th><th>Max</th><th>StdDev</th></tr></thead><tbody>\n{rows}</tbody></table>\n")

def _render_report_footer(combination_id: str, session_date: date) -> str:
    gen = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""\
<footer>
  <p><strong>Methodology</strong></p>
  <ul>
    <li><strong>Downtime</strong>: first client query failure → first client success after last failure.</li>
    <li>Client fires INSERT heartbeats every 100 ms; observer polls REST APIs every 200 ms.</li>
    <li>Charts embedded as base64 PNG (kaleido required).</li>
  </ul>
  <p>Generated: {_h(gen)} &nbsp;|&nbsp; patroni-routing-bench
     &nbsp;|&nbsp; combination: <code>{_h(combination_id)}</code>
     &nbsp;|&nbsp; session: {_h(str(session_date))}</p>
</footer>
"""

# ── Batch report: constants and helpers ───────────────────────────────────────
HAPROXY_FAMILY = ["06-haproxy-rest-polling", "06-haproxy-rest-polling-tuned",
                  "07-consul-template-reload", "08-consul-template-runtime-api",
                  "09-patroni-callback-haproxy"]
VIP_FAMILY     = ["03-vip-manager-poll", "04-vip-patroni-callback"]
LAYER_LABELS   = {
    "01-libpq-multihost":             "libpq (client-side)",
    "02-consul-dns":                  "Consul DNS",
    "03-vip-manager-poll":            "VIP (poll)",
    "04-vip-patroni-callback":        "VIP (Patroni callback)",
    "05-bgp-anycast":                 "BGP anycast",
    "06-haproxy-rest-polling":        "HAProxy REST poll",
    "06-haproxy-rest-polling-tuned":  "HAProxy REST poll (tuned)",
    "07-consul-template-reload":      "Consul Template reload",
    "08-consul-template-runtime-api": "Consul Template runtime API",
    "09-patroni-callback-haproxy":    "Patroni callback → HAProxy",
    "10-consul-connect-envoy":        "Consul Connect / Envoy",
}
SCENARIO_ORDER = ["hard_stop", "hard_kill", "postgres_crash", "switchover", "pause"]

_BATCH_CSS = """\
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
     background:#f7f8fa;color:#1a1a2e;font-size:14px}
header{background:#1a1a2e;color:#fff;padding:24px 36px}
header h1{font-size:1.6rem}header p{margin-top:6px;opacity:0.75;font-size:0.9rem}
.container{max-width:1200px;margin:0 auto;padding:24px 36px}
h2{font-size:1.25rem;border-left:4px solid #4c9be8;padding-left:10px;margin:32px 0 14px}
h3{font-size:1rem;margin:22px 0 8px;color:#333}
table{border-collapse:collapse;width:100%;margin-bottom:16px;font-size:13px}
th,td{border:1px solid #dde;padding:7px 12px;text-align:left}
th{background:#1a1a2e;color:#fff}tr:nth-child(even){background:#f0f2f8}
td.pass{color:#2a8a4a;font-weight:bold}td.fail{color:#c0392b;font-weight:bold}
.meta{background:#fff;border:1px solid #dde;border-radius:6px;padding:14px 20px;
      margin-bottom:20px;display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:8px}
.meta-item label{font-size:0.78rem;color:#777;display:block}.meta-item span{font-weight:600}
.combo-links a{display:inline-block;margin:4px 8px 4px 0;padding:4px 10px;
               background:#4c9be8;color:#fff;border-radius:4px;text-decoration:none;font-size:12px}
footer{text-align:center;padding:24px;color:#888;font-size:12px}
"""

def _git_rev() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception: return "unknown"

def _docker_version() -> str:
    try:
        return subprocess.check_output(["docker", "version", "--format", "{{.Server.Version}}"],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception: return "unknown"

def _to_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series.replace({"—": None}), errors="coerce")

_WATERFALL_SQL = """
WITH base AS (
    SELECT tr.id AS run_id, tr.combination_id,
        MIN(ce.ts) FILTER (WHERE NOT ce.success)                                       AS t_first_fail,
        MIN(ce.ts) FILTER (WHERE ce.success AND ce.ts > (
            SELECT MAX(ts) FROM client_events WHERE test_run_id = tr.id AND NOT success
        ))                                                                             AS t_client_recover
    FROM test_runs tr JOIN client_events ce ON ce.test_run_id = tr.id
    WHERE tr.combination_id = %s
    GROUP BY tr.id, tr.combination_id
    HAVING MIN(ce.ts) FILTER (WHERE NOT ce.success) IS NOT NULL
),
milestones AS (
    SELECT b.run_id, b.t_first_fail, b.t_client_recover,
        MIN(oe.ts) FILTER (WHERE oe.component='postgres'
            AND oe.event_type IN ('pg_promote_requested', 'pg_promote_detected'))       AS t_pg_promote,
        MIN(oe.ts) FILTER (WHERE oe.component='patroni'
            AND oe.event_type='role_change' AND oe.new_value='primary'
            AND oe.ts > b.t_first_fail)                                                AS t_patroni_primary,
        MIN(oe.ts) FILTER (WHERE oe.component='consul'
            AND oe.event_type='leader_key_created' AND oe.ts > b.t_first_fail)        AS t_consul_key,
        MIN(oe.ts) FILTER (WHERE oe.component='haproxy'
            AND oe.event_type='backend_state_change' AND oe.new_value='UP'
            AND (oe.detail IS NULL OR oe.detail LIKE '%%primary_backend%%')
            AND oe.ts > b.t_first_fail)                                                AS t_haproxy_up,
        MIN(oe.ts) FILTER (WHERE oe.component='postgres'
            AND oe.event_type='pg_ready_accept_connections'
            AND oe.ts > b.t_first_fail)                                                AS t_pg_ready
    FROM base b LEFT JOIN observer_events oe
        ON oe.test_run_id = b.run_id AND oe.ts > b.t_first_fail
    GROUP BY b.run_id, b.t_first_fail, b.t_client_recover
)
SELECT run_id,
    EXTRACT(EPOCH FROM (t_pg_promote      - t_first_fail))::float AS dt_t0,
    EXTRACT(EPOCH FROM (t_patroni_primary - t_first_fail))::float AS dt_t1,
    EXTRACT(EPOCH FROM (t_consul_key      - t_first_fail))::float AS dt_t2,
    EXTRACT(EPOCH FROM (t_haproxy_up      - t_first_fail))::float AS dt_t3,
    EXTRACT(EPOCH FROM (t_pg_ready        - t_first_fail))::float AS dt_t4,
    EXTRACT(EPOCH FROM (t_client_recover  - t_first_fail))::float AS dt_tc
FROM milestones ORDER BY run_id
"""

def _compute_waterfall(conn, combination_id: str) -> Optional[dict]:
    try:
        with conn.cursor() as cur:
            cur.execute(_WATERFALL_SQL, [combination_id])
            rows = cur.fetchall()
    except Exception as e:
        print(f"  [WARN] Waterfall query failed for {combination_id}: {e}", file=sys.stderr)
        return None
    if not rows: return None
    buckets: dict = {"T0": [], "T1": [], "T2": [], "T3": [], "T4": [], "Tc": []}
    keys = {"T0": 1, "T1": 2, "T2": 3, "T3": 4, "T4": 5, "Tc": 6}
    for row in rows:
        for phase, idx in keys.items():
            v = row[idx]
            if v is not None and not (isinstance(v, float) and math.isnan(v)):
                buckets[phase].append(float(v))
    return {p: statistics.median(vals) if vals else None for p, vals in buckets.items()}

# ── Batch report: chart sections ──────────────────────────────────────────────
def _render_batch_heatmap(df: pd.DataFrame) -> str:
    success = df[df["status"] == "SUCCESS"].copy()
    success["downtime_s"] = _to_numeric(success["downtime_s"])
    pivot = (success.groupby(["combo_dir", "scenario"])["downtime_s"]
             .median().unstack("scenario")
             .reindex(columns=[s for s in SCENARIO_ORDER if s in success["scenario"].unique()]))
    if pivot.empty: return "<p><em>No successful runs to plot.</em></p>"
    pivot = pivot.loc[pivot.mean(axis=1).sort_values().index]

    def _safe(v):
        try:
            f = float(v)
            return "" if math.isnan(f) else f"{f:.1f}"
        except (TypeError, ValueError):
            return ""

    z_vals   = [[float(v) if v is not None else float("nan") for v in row] for row in pivot.values.tolist()]
    text_vals = [[_safe(v) for v in row] for row in pivot.values.tolist()]
    y_labels  = [LAYER_LABELS.get(r, r) for r in pivot.index]
    fig = go.Figure(go.Heatmap(
        z=z_vals, x=pivot.columns.tolist(), y=y_labels,
        colorscale="RdYlGn_r", text=text_vals, texttemplate="%{text}",
        colorbar=dict(title="Median<br>downtime (s)"),
    ))
    fig.update_layout(
        title="Median failover downtime (s) — combinations × scenarios",
        width=max(600, len(pivot.columns) * 150), height=max(350, len(pivot.index) * 45 + 100),
        margin=dict(l=220, r=60, t=60, b=80),
        font=dict(family=FONT_FAMILY), plot_bgcolor=WHITE, paper_bgcolor=WHITE,
    )
    return _plotly_html(fig)

def _render_batch_scenario_bars(df: pd.DataFrame) -> str:
    success = df[df["status"] == "SUCCESS"].copy()
    success["downtime_s"]     = _to_numeric(success["downtime_s"])
    success["failed_queries"] = _to_numeric(success["failed_queries"])
    parts = []
    for scenario in [s for s in SCENARIO_ORDER if s in success["scenario"].unique()]:
        sub = success[success["scenario"] == scenario]
        if sub.empty: continue
        med_dt = sub.groupby("combo_dir")["downtime_s"].median().sort_values()
        med_fq = sub.groupby("combo_dir")["failed_queries"].median().reindex(med_dt.index)
        labels = [LAYER_LABELS.get(c, c) for c in med_dt.index]
        fig = go.Figure()
        fig.add_trace(go.Bar(
            name="Downtime (s)", x=labels, y=med_dt.values,
            marker_color="#4c9be8",
            text=[f"{v:.1f}s" for v in med_dt.values],
            textposition="outside",
        ))
        fig.add_trace(go.Bar(
            name="Failed queries", x=labels, y=med_fq.values,
            marker_color="#e87c4c",
            text=[f"{int(v)}" for v in med_fq.values],
            textposition="outside",
        ))
        fig.update_layout(
            title=f"Scenario: {scenario}", barmode="group",
            yaxis=dict(title="Value"),
            width=max(600, len(labels) * 90), height=420,
            font=dict(family=FONT_FAMILY), plot_bgcolor=WHITE, paper_bgcolor=WHITE,
            margin=dict(l=60, r=60, t=60, b=130),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        )
        parts.append(f"<h3>{_h(scenario)}</h3>" + _plotly_html(fig))
    return "\n".join(parts)

def _render_batch_family_charts(df: pd.DataFrame) -> str:
    success = df[df["status"] == "SUCCESS"].copy()
    success["downtime_s"] = _to_numeric(success["downtime_s"])
    html = ""

    def _hbar(title, data, full_df):
        med = data.groupby("combo_dir")["downtime_s"].median().sort_values()
        labels = [LAYER_LABELS.get(c, c) for c in med.index]
        annotations = []
        for c in med.index:
            total = len(full_df[full_df["combo_dir"] == c])
            ok = len(data[data["combo_dir"] == c])
            annotations.append(f"{ok}/{total}")
        bar_texts = [f"{v:.1f}s ({a})" for v, a in zip(med.values, annotations)]
        fig = go.Figure(go.Bar(
            x=med.values, y=labels, orientation="h",
            text=bar_texts, textposition="outside",
            marker_color="#4c9be8",
        ))
        fig.update_layout(title=title, xaxis_title="Median downtime (s)",
                          width=max(600, 800), height=max(280, len(labels) * 55 + 80),
                          font=dict(family=FONT_FAMILY), plot_bgcolor=WHITE, paper_bgcolor=WHITE,
                          margin=dict(l=210, r=120, t=60, b=40))
        return _plotly_html(fig)

    ha_data  = success[success["combo_dir"].isin(HAPROXY_FAMILY)]
    vip_data = success[success["combo_dir"].isin(VIP_FAMILY)]
    if not ha_data.empty:
        html += "<h3>HAProxy Variants</h3>" + _hbar("HAProxy routing family — median downtime", ha_data, df)
    if not vip_data.empty:
        html += "<h3>VIP Manager Variants</h3>" + _hbar("VIP routing family — poll vs callback", vip_data, df)
    if not success.empty:
        html += "<h3>Overall Leaderboard</h3>" + _hbar("Overall leaderboard — all combinations", success, df)
    return html

def _render_batch_waterfall(waterfall_data: dict) -> str:
    if not waterfall_data:
        return "<p><em>TimescaleDB not available or no data.</em></p>"
    html = ""
    for combo_id, medians in sorted(waterfall_data.items()):
        label = LAYER_LABELS.get(combo_id, combo_id)
        tc = medians.get("Tc")
        t0 = medians.get("T0")
        t4 = medians.get("T4")
        if tc is None:
            continue
        phases = []
        if t4 is not None and t0 is not None:
            phases.append(("DCS + Election", t4, "#e67e22"))
            phases.append(("Routing update", max(0, tc - t4), "#3498db"))
        else:
            phases.append(("Total failover", tc, "#e67e22"))

        fig = go.Figure()
        cumulative = 0
        for name, duration, color in phases:
            fig.add_trace(go.Bar(
                name=name, y=[label], x=[duration], orientation="h",
                marker_color=color, base=[cumulative],
                text=[f"{duration:.1f}s"], textposition="inside",
                insidetextanchor="middle",
            ))
            cumulative += duration
        fig.update_layout(
            barmode="stack",
            xaxis_title="Seconds",
            width=700, height=120,
            font=dict(family=FONT_FAMILY), plot_bgcolor=WHITE, paper_bgcolor=WHITE,
            margin=dict(l=200, r=80, t=10, b=30),
            showlegend=True,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        )
        t1 = medians.get("T1")
        t2 = medians.get("T2")
        t3 = medians.get("T3")
        trows = ""
        if t2 is not None:
            trows += f"<tr><td>DCS detected</td><td>{t2:.1f}s</td></tr>"
        if t0 is not None:
            trows += f"<tr><td>PG promoted</td><td>{t0:.1f}s</td></tr>"
        if t1 is not None:
            trows += f"<tr><td>Patroni promoted</td><td>{t1:.1f}s</td></tr>"
        if t3 is not None:
            trows += f"<tr><td>Routing updated</td><td>{t3:.1f}s</td></tr>"
        trows += f"<tr><td><strong>Client recovered</strong></td><td><strong>{tc:.1f}s</strong></td></tr>"
        html += (f"<h3>{_h(label)}</h3>" + _plotly_html(fig)
                 + f"<table><thead><tr><th>Milestone</th><th>Offset from first failure</th></tr></thead>"
                 f"<tbody>{trows}</tbody></table>")
    return html

def _render_batch_summary_table(df: pd.DataFrame) -> str:
    success = df[df["status"] == "SUCCESS"].copy()
    success["downtime_s"]     = _to_numeric(success["downtime_s"])
    success["failed_queries"] = _to_numeric(success["failed_queries"])
    rows = ""
    for combo in sorted(df["combo_dir"].unique()):
        sub = success[success["combo_dir"] == combo]
        total, ok = len(df[df["combo_dir"] == combo]), len(sub)
        if ok > 0:
            med_dt = sub["downtime_s"].median()
            med_fq = sub["failed_queries"].median()
            try:
                dt_str = f"{med_dt:.2f}s" if not math.isnan(float(med_dt)) else "—"
                fq_str = str(int(med_fq)) if not math.isnan(float(med_fq)) else "—"
            except (TypeError, ValueError):
                dt_str = fq_str = "—"
            sc, sl = "pass", f"{ok}/{total} passed"
        else:
            dt_str, fq_str, sc, sl = "—", "—", "fail", f"0/{total} passed"
        rows += (f"<tr><td>{_h(combo)}</td><td>{_h(LAYER_LABELS.get(combo, combo))}</td>"
                 f"<td class='{sc}'>{sl}</td><td>{dt_str}</td><td>{fq_str}</td></tr>\n")
    return (f"<table><thead><tr><th>Combination ID</th><th>Description</th><th>Status</th>"
            f"<th>Median downtime</th><th>Median failed queries</th></tr></thead>"
            f"<tbody>\n{rows}</tbody></table>\n")

# ── Subcommand handlers ───────────────────────────────────────────────────────
def cmd_iteration(args):
    conn = get_connection()
    test_run_id, combination_id = resolve_test_run(conn, args.test_run_id)
    print(f"Test run:    {test_run_id}")
    print(f"Combination: {combination_id}")

    obs_df = load_observer_events(conn, combination_id, test_run_id)
    cli_df = load_client_events(conn, combination_id, test_run_id)
    if len(cli_df) > 5000 or (not cli_df.empty
            and (cli_df["ts"].max() - cli_df["ts"].min()).total_seconds() > 120):
        anchor = find_failover_anchor(conn, combination_id, test_run_id)
        if anchor:
            ws, we = anchor - pd.Timedelta(seconds=15), anchor + pd.Timedelta(seconds=30)
            obs_df = load_windowed_observer(conn, combination_id, test_run_id, ws, we)
            cli_df = load_windowed_client(conn, combination_id, test_run_id, ws, we)
    if obs_df.empty:
        print("No observer events found.", file=sys.stderr); sys.exit(1)

    fw = load_failover_window(conn, combination_id, test_run_id)
    downtime_s = float(fw["downtime_ms"]) / 1000.0 if fw and fw.get("downtime_ms") else None
    if downtime_s is None:
        ms0 = extract_milestones(obs_df, cli_df)
        if "first_client_failure" in ms0 and "first_recovery" in ms0:
            downtime_s = (ms0["first_recovery"] - ms0["first_client_failure"]).total_seconds()

    out_dir = Path(args.output_dir)
    title   = f"Failover Timeline — {combination_id}"
    ms      = extract_milestones(obs_df, cli_df)

    print("\n--- Gantt chart ---")
    gantt = build_gantt_chart(obs_df, cli_df, combination_id, downtime_s, title)
    _save_png(gantt, out_dir / "failover_gantt.png")

    print("\n--- Phase breakdown ---")
    phase_fig, phases = build_phase_chart(ms, combination_id,
                                          f"Failover Phase Breakdown — {combination_id}")
    if phase_fig:
        _save_png(phase_fig, out_dir / "failover_phases.png")
    else:
        print("  Not enough milestones for phase chart.")

    print("\n--- Overlapping phases ---")
    ov_phases, ov_markers = extract_overlap_phases(obs_df, cli_df)
    ov_fig = build_overlap_phase_chart(ov_phases, ov_markers, combination_id,
                                        f"Failover Phases (Overlapping) — {combination_id}")
    if ov_fig:
        _save_png(ov_fig, out_dir / "failover_phases_overlap.png")
    else:
        print("  Not enough events for overlapping phase chart.")

    if downtime_s: print(f"\nTotal downtime: {downtime_s:.1f}s")
    conn.close()
    print("\nDone!")


def cmd_combo_report(args):
    combination_id = args.combination_id
    session_dir    = Path(args.session_dir)
    out_path       = Path(args.output)

    try:
        session_date = _parse_session_date(session_dir.name.split("_")[0])
    except ValueError as e:
        print(f"Error: cannot parse date from session-dir '{session_dir.name}': {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Combination:  {combination_id}")
    print(f"Session date: {session_date}")
    print(f"Session dir:  {session_dir}")
    print(f"Output:       {out_path}")

    conn     = get_connection()
    runs_df  = _load_session_runs(conn, combination_id, session_date)
    if runs_df.empty:
        print(f"Error: no test runs found for '{combination_id}' on {session_date}", file=sys.stderr)
        sys.exit(1)
    print(f"Found {len(runs_df)} test run(s)")

    patroni_cfg = _load_patroni_config(combination_id)
    iterations: list  = []
    iter_sections: list = []

    for i, (_, run_row) in enumerate(runs_df.iterrows(), start=1):
        run_id   = run_row["id"]
        scenario = run_row["failover_type"] or "unknown"
        print(f"  [{i}/{len(runs_df)}] {run_id}  ({scenario})")
        obs_df, cli_df, fw = load_run_data(conn, combination_id, run_id)
        downtime_s  = float(fw["downtime_ms"]) / 1000.0 if fw and fw.get("downtime_ms") else None
        total_fails = fw.get("total_failures", "—") if fw else "—"
        it_status   = "SUCCESS" if downtime_s is not None else (
            "SUCCESS" if not cli_df.empty and cli_df["success"].all() else "UNKNOWN"
        )
        leader = _infer_killed_leader(obs_df)
        iterations.append({"num": i, "scenario": scenario, "leader": leader,
                            "downtime":      f"{downtime_s:.1f}" if downtime_s else "—",
                            "failed_queries": int(total_fails) if total_fails != "—" else "—",
                            "status": it_status, "run_id": run_id})
        preloaded = _load_iter_charts(session_dir, i, scenario)
        if preloaded:
            print(f"    loaded {len(preloaded)} chart(s) from iter{i}_{scenario}/")
        else:
            print(f"    no pre-rendered charts for iter{i}_{scenario} — will show placeholders")
        iter_sections.append(_render_iteration_section(
            i, run_row, obs_df, cli_df, fw, it_status, leader, preloaded_charts=preloaded,
        ))

    doc = (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
        f"<title>Failover Report — {_h(combination_id)} — {_h(str(session_date))}</title>\n"
        f"<style>{_CSS}</style>\n</head>\n<body>\n"
        + _render_header(combination_id, session_date, patroni_cfg, runs_df, iterations)
        + _render_summary_table(iterations)
        + "\n<h2>Per-Iteration Detail</h2>\n"
        + "\n".join(iter_sections)
        + _render_comparison_section(iterations)
        + _render_report_footer(combination_id, session_date)
        + "\n</body>\n</html>\n"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc, encoding="utf-8")
    print(f"\nReport saved: {out_path}")
    conn.close()


def cmd_batch_report(args):
    csv_path = Path(args.batch_csv)
    if not csv_path.exists():
        sys.exit(f"ERROR: batch CSV not found: {csv_path}")
    df = pd.read_csv(csv_path)
    if df.empty:
        sys.exit("ERROR: batch CSV is empty")
    out_path  = Path(args.output)
    batch_ts  = csv_path.parent.name.replace("batch_", "").replace("_", " ", 1)
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    conn = None
    try:
        conn = get_connection()
        print("Connected to TimescaleDB")
    except Exception as e:
        print(f"[WARN] TimescaleDB unavailable: {e} — waterfall skipped", file=sys.stderr)

    waterfall_data: dict = {}
    if conn:
        for combo_id in sorted(df["combo_dir"].unique()):
            medians = _compute_waterfall(conn, combo_id)
            if medians:
                waterfall_data[combo_id] = medians
                print(f"  {combo_id}: ok")
            else:
                print(f"  {combo_id}: no data")
        conn.close()

    link_html = '<div class="combo-links">'
    for _, row in df.drop_duplicates("combo_dir").iterrows():
        session = str(row.get("session_folder", ""))
        rp = Path(session) / "report.html" if session else None
        if rp and rp.exists():
            rel = os.path.relpath(rp, out_path.parent)
            link_html += f'<a href="{rel}">{_h(row["combo_dir"])}</a>'
        else:
            link_html += (f'<span style="display:inline-block;margin:4px 8px 4px 0;padding:4px 10px;'
                          f'background:#ccc;border-radius:4px;font-size:12px">'
                          f'{_h(row["combo_dir"])}</span>')
    link_html += "</div>"

    html = (f"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
            f"<meta charset=\"UTF-8\">"
            f"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
            f"<title>Batch Report — patroni-routing-bench</title>\n"
            f"<style>{_BATCH_CSS}</style>\n</head>\n<body>\n"
            f"<header><h1>Patroni Routing Benchmark — Batch Report</h1>"
            f"<p>Generated {generated} &nbsp;|&nbsp; Batch: {batch_ts}</p></header>\n"
            f"<div class=\"container\">\n"
            f"<div class=\"meta\">"
            f"<div class=\"meta-item\"><label>Combinations run</label><span>{df['combo_dir'].nunique()}</span></div>"
            f"<div class=\"meta-item\"><label>Total iterations</label><span>{len(df)}</span></div>"
            f"<div class=\"meta-item\"><label>Successful</label><span>{(df['status']=='SUCCESS').sum()}</span></div>"
            f"<div class=\"meta-item\"><label>Scenarios</label><span>{', '.join(sorted(df['scenario'].unique()))}</span></div>"
            f"<div class=\"meta-item\"><label>Git revision</label><span>{_git_rev()}</span></div>"
            f"</div>\n"
            f"<h2>1. Results Summary</h2>\n{_render_batch_summary_table(df)}\n"
            f"<h2>2. Downtime Heatmap — Combination × Scenario</h2>\n{_render_batch_heatmap(df)}\n"
            f"<h2>3. Per-Scenario Comparison</h2>\n{_render_batch_scenario_bars(df)}\n"
            f"<h2>4. Routing Layer Families</h2>\n{_render_batch_family_charts(df)}\n"
            f"<h2>5. Failover Waterfall Timings</h2>\n{_render_batch_waterfall(waterfall_data)}\n"
            f"<h2>6. Methodology &amp; Environment</h2>\n"
            f"<table><thead><tr><th>Parameter</th><th>Value</th></tr></thead><tbody>\n"
            f"<tr><td>Batch CSV</td><td>{_h(str(csv_path))}</td></tr>\n"
            f"<tr><td>Generated</td><td>{generated}</td></tr>\n"
            f"<tr><td>Git revision</td><td>{_git_rev()}</td></tr>\n"
            f"<tr><td>Docker version</td><td>{_docker_version()}</td></tr>\n"
            f"<tr><td>Downtime measurement</td><td>First client failure → first success after last failure</td></tr>\n"
            f"<tr><td>Waterfall T0</td><td>postgres pg_promote_requested</td></tr>\n"
            f"<tr><td>Waterfall Tc</td><td>First client success after last failure</td></tr>\n"
            f"</tbody></table>\n"
            f"</div>\n<footer>patroni-routing-bench &mdash; batch report</footer>\n</body>\n</html>\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    print(f"Batch report saved: {out_path}")


def cmd_legacy(args):
    conn = get_connection()
    print("Connected to TimescaleDB")

    if args.compare:
        print("\n--- Comparison: Downtime ---")
        generate_comparison_downtime(conn)
        print("\n--- Comparison: Phase Breakdown ---")
        generate_comparison_phases(conn)
        conn.close()
        print("\nDone!")
        return

    combination_id = args.combination_id
    test_run_id    = args.test_run_id

    if test_run_id and not combination_id:
        with conn.cursor() as cur:
            cur.execute("SELECT DISTINCT combination_id FROM observer_events WHERE test_run_id = %s",
                        (test_run_id,))
            row = cur.fetchone()
        if not row:
            print(f"Error: test_run_id '{test_run_id}' not found", file=sys.stderr); sys.exit(1)
        combination_id = row[0]

    if not combination_id:
        print("Error: --combination-id or --test-run-id required", file=sys.stderr); sys.exit(1)

    # Bug fix: resolve latest test_run_id when empty
    if not test_run_id:
        test_run_id = _resolve_latest_trid(conn, combination_id)
        if not test_run_id:
            print(f"No test runs found for combination '{combination_id}'.", file=sys.stderr)
            sys.exit(1)

    print(f"Combination: {combination_id}")
    print(f"Test run:    {test_run_id}")

    obs_df, cli_df, fw = load_run_data(conn, combination_id, test_run_id)
    if obs_df.empty:
        print("No observer events found.", file=sys.stderr); sys.exit(1)

    downtime_s = float(fw["downtime_ms"]) / 1000.0 if fw and fw.get("downtime_ms") else None
    ms = extract_milestones(obs_df, cli_df)
    title = f"Failover Timeline — {combination_id}"
    run_label = test_run_id or "latest"

    print("\n--- Gantt chart ---")
    gantt = build_gantt_chart(obs_df, cli_df, combination_id, downtime_s, title)
    _save_legacy(gantt, f"{combination_id}_{run_label}_gantt")

    print("\n--- Phase breakdown ---")
    phase_fig, _ = build_phase_chart(ms, combination_id,
                                      f"Failover Phase Breakdown — {combination_id}")
    if phase_fig:
        _save_legacy(phase_fig, f"{combination_id}_{run_label}_phases")

    print("\n--- Overlapping phases ---")
    ov_phases, ov_markers = extract_overlap_phases(obs_df, cli_df)
    ov_fig = build_overlap_phase_chart(ov_phases, ov_markers, combination_id,
                                        f"Failover Phases (Overlapping) — {combination_id}")
    if ov_fig:
        _save_legacy(ov_fig, f"{combination_id}_{run_label}_phases_overlap")

    conn.close()
    print("\nDone!")

# ── CLI entry point ───────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="patroni-routing-bench chart generation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Subcommands:\n"
            "  iteration     Generate per-iteration PNGs (Gantt, phases, overlap)\n"
            "  combo-report  Generate self-contained HTML session report\n"
            "  batch-report  Generate cross-combo batch HTML report\n\n"
            "Legacy (no subcommand):\n"
            "  --combination-id ID   Charts for the latest run of a combination\n"
            "  --test-run-id ID      Charts for a specific test run\n"
            "  --compare             Cross-combination comparison charts\n"
        ),
    )
    # Legacy flags (used when no subcommand)
    parser.add_argument("--test-run-id",    default="", help="Specific test run ID")
    parser.add_argument("--combination-id", default="", help="Combination ID (uses latest run)")
    parser.add_argument("--compare", action="store_true", help="Generate comparison charts")

    subs = parser.add_subparsers(dest="subcommand")

    p_iter = subs.add_parser("iteration",
                              help="Generate per-iteration PNGs for one test run")
    p_iter.add_argument("--test-run-id",  required=True, help="Test run ID to visualize")
    p_iter.add_argument("--output-dir",   default="./output",
                        help="Directory for output PNGs (default: ./output)")

    p_combo = subs.add_parser("combo-report",
                               help="Generate self-contained HTML session report")
    p_combo.add_argument("--combination-id", required=True,
                         help="Combination identifier (e.g. 06-haproxy-rest-polling)")
    p_combo.add_argument("--session-dir",    required=True,
                         help="Session directory (e.g. /results/06-haproxy.../20260421_214658)")
    p_combo.add_argument("--output",         required=True, help="Output HTML file path")

    p_batch = subs.add_parser("batch-report",
                               help="Generate cross-combo batch HTML report")
    p_batch.add_argument("--batch-csv",  required=True, help="Path to results.csv from run_batch.sh")
    p_batch.add_argument("--batch-dir",  required=True, help="Batch results directory (for context)")
    p_batch.add_argument("--output",     required=True, help="Output HTML file path")

    args = parser.parse_args()

    if args.subcommand == "iteration":
        cmd_iteration(args)
    elif args.subcommand == "combo-report":
        cmd_combo_report(args)
    elif args.subcommand == "batch-report":
        cmd_batch_report(args)
    else:
        if not args.test_run_id and not args.combination_id and not args.compare:
            parser.print_help()
            sys.exit(1)
        cmd_legacy(args)


if __name__ == "__main__":
    main()
